import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/app/_redux/provider";
import "./globals.css";
import Navbar from "@/app/components/layout/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar>
            {children}
          </Navbar>
          </ReduxProvider>
      </body>
    </html>
  );
}
